plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id "me.modmuss50.mod-publish-plugin" version "1.1.0"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group


base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven { url = 'https://maven.minecraftforge.net' }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	compileOnly "net.minecraftforge:javafmllanguage:1.21.6-56.0.0"
	compileOnly "net.minecraftforge:fmlcore:1.21.6-56.0.0"
	compileOnly 'net.minecraftforge:eventbus:7.0.2'
	
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand(
                "version": inputs.properties.version,
                "id": project.archives_base_name,
                "name": project.modname,
                "license": project.license,
                "authors": project.authors
        )
	}

    filesMatching("META-INF/neoforge.mods.toml") {
        expand (
                "mod_issue_tracker": project.issue_tracker,
                "mod_license": project.license,
                "mod_id": project.archives_base_name,
                "mod_version": project.version,
                "mod_name": project.modname,
                "mod_description": project.description,
                "mod_author": project.authors
        )

    }

    filesMatching("META-INF/mods.toml") {
        expand (
                "mod_issue_tracker": project.issue_tracker,
                "mod_license": project.license,
                "mod_id": project.archives_base_name,
                "mod_version": project.version,
                "mod_name": project.modname,
                "mod_description": project.description,
                "mod_author": project.authors
        )

    }

    filesMatching("quilt.mod.json") {
        expand(
                "version": inputs.properties.version,
                "id": project.archives_base_name,
                "name": project.modname,
                "license": project.license,
                "group": project.maven_group,
                "description": project.description
        )
    }





}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	//withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}

	manifest {
		attributes(
				'MixinConfigs': project.archives_base_name + ".forge.mixins.json"
		)
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

publishMods {
	file = jar.archiveFile

	var changelogText = project.findProperty("releaseChangelog") ?: ""
	changelog = changelogText

	type = STABLE
	modLoaders.add("fabric")
	modLoaders.add("quilt")
	modLoaders.add("neoforge")

	curseforge {
		projectId = "1398594"
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		minecraftVersions.add("26.1-snapshot")
	}
	modrinth {
		projectId = "soBfQALz"
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		minecraftVersions.add("26.1-snapshot-1")
		minecraftVersions.add("26.1-snapshot-2")
		minecraftVersions.add("26.1-snapshot-3")
		minecraftVersions.add("26.1-snapshot-4")
		minecraftVersions.add("26.1-snapshot-5")
		minecraftVersions.add("26.1-snapshot-6")
		minecraftVersions.add("26.1-snapshot-7")


	}
}